---
root:

    - match: "^((?:(?:[a-zA-Z]|[a-zA-Z][a-zA-Z0-9\\-]*\
        [a-zA-Z0-9])\\.)*(?:[A-Za-z]|[A-Za-z][A-Za-z0-9\\-]*[A-Za-z0-9])\\b"
      replace: '{t.green}\1{t.normal}'
      continue: true

    - match: '^(\d{1,3}(?:\.\d+){3})'
      replace: '{t.green}\1{t.normal}'
      continue: true

    - match: '"([^"]+)"'
      replace: '"{t.red}\1{t.normal}"'
      continue: true

    - match: '" (\d+) (\d+) "'
      replace: '" {t.blue}\1 {t.cyan} \2{t.normal} "'
