---
root:
    - match: '^(running)(.*)'
      replace: '*** {t.green}\1{t.normal}\2'

    - match: '^(writing)(.*)'
      replace: '>>> {t.yellow}\1{t.normal}\2'

    - match: '^(reading)(.*)'
      replace: '<<< {t.blue}\1{t.normal}\2'

    - match: '^(Processing dependencies for)(.*)'
      replace: '{t.green}\1{t.normal}\2'
      push: dependencies

    - match: '^(Installing.*)'
      replace: '>>> {t.green}\1{t.normal}'

dependencies:
    - match: '^(Finished processing dependencies for)(.*)'
      replace: '{t.green}\1{t.normal}\2'
      pop: true

    - match: '^(Searching for )(.*)$'
      replace: '\1{t.blue}\2{t.normal}'
      push: dependency

dependency:
    - match: '(.*)'
      replace: ' | \1'
      continue: true

    - match: '^ \| (Installing.*)'
      replace: ' | >>> {t.green}\1{t.normal}'

    - match: '^ \| (Running.*)'
      replace: ' | {t.green}\1{t.normal}'

    - match: '^ \| (Best match.*)'
      replace: ' | {t.green}\1{t.normal}'

    - match: '^ \| (WARNING|warning)'
      replace: ' | {t.yellow}\1{t.normal}'

    - match: '^ \| Installed(.*)'
      replace: ' | Installed\1\n'
      pop: true
